name: Sync Fork

on:
  schedule:
    - cron: '0 13 */7 * *'
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: tgymnich/fork-sync@v1.9
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          owner: david082321
          base: main
          head: main
        continue-on-error: true
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/keepalive-workflow@v1
